// ITEM TYPES (TEMPLATE STATE)
export const GET_ITEMS = "GET_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const ITEMS_LOADING = "ITEMS_LOADING";

// USERS TYPES (ALL USERS)
export const GET_USERS = "GET_USERS";
export const USERS_LOADING = "USERS_LOADING";
