// USERS TYPES (ALL USERS)
export const GET_USERS = "GET_USERS";
export const USERS_LOADING = "USERS_LOADING";

// USER TYPES (AUTH)
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// ERROR TYPES
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// SOCKET TYPES
export const ASSIGN_SOCKET = "ASSIGN_SOCKET";
export const SOCKET_MESSAGE_RECEIVED = "SOCKET_MESSAGE_RECEIVED";
export const SOCKET_MESSAGE_SEND = "SOCKET_MESSAGE_SEND";
export const SOCKET_ADD_USER = "SOCKET_ADD_USER";
export const SOCKET_REMOVE_USER = "SOCKET_REMOVE_USER";
export const SOCKET_USERS_RECEIVED = "SOCKET_USERS_RECEIVED";

// ROOM TYPES
export const GET_ROOMS = "GET_ROOMS";
export const GET_ROOM = "GET_ROOM";
export const ADD_ROOM = "ADD_ROOM";
export const DELETE_ROOM = "DELETE_ROOM";
export const ROOMS_LOADING = "ROOMS_LOADING";
export const ADD_ROOM_MEMBER = "ADD_ROOM_MEMBER";
export const REMOVE_ROOM_MEMBER = "REMOVE_ROOM_MEMBER";
export const GET_ROOM_MEMBERS = "GET_ROOM_MEMBERS";
